import { RoutesService, eLayoutType } from '@abp/ng.core';
import { inject, provideAppInitializer } from '@angular/core';

export const APP_ROUTE_PROVIDER = [
  provideAppInitializer(() => {
    configureRoutes();
  }),
];

function configureRoutes() {
  const routes = inject(RoutesService);
  routes.add([
    // Home
    {
      path: '/',
      name: '::Menu:Home',
      iconClass: 'fas fa-home',
      order: 1,
      layout: eLayoutType.application,
    },
    // Reception
    {
      name: '::Menu:Reception',
      iconClass: 'fas fa-hospital-user',
      order: 10,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Reception',
    },
    {
      path: '/reception/laboratory-reception',
      name: '::Menu:Tickets',
      parentName: '::Menu:Reception',
      iconClass: 'fas fa-list-alt',
      order: 1,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Reception.Tickets',
    },
    {
      path: '/patients',
      name: '::Menu:Patients',
      parentName: '::Menu:Reception',
      iconClass: 'fas fa-user-injured',
      order: 2,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Patients',
    },
    // Appointments
    {
      name: '::Menu:Appointments',
      iconClass: 'fas fa-calendar-check',
      order: 20,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Appointments',
    },
    {
      path: '/appointments/booking',
      name: '::Menu:BookNewAppointment',
      parentName: '::Menu:Appointments',
      iconClass: 'fas fa-calendar-plus',
      order: 21,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Appointments.Create',
    },
    {
      path: '/appointments/my-appointments',
      name: '::Menu:MyAppointments',
      parentName: '::Menu:Appointments',
      iconClass: 'fas fa-list-alt',
      order: 22,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Appointments',
    },
    // Accounts (Financials)
    {
      name: '::Menu:Accounts',
      iconClass: 'fas fa-file-invoice-dollar',
      order: 30,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Billing',
    },

    {
      path: '/accounting/chart-of-accounts',
      name: '::Menu:ChartOfAccounts',
      parentName: '::Menu:Accounts',
      iconClass: 'fas fa-sitemap',
      order: 31,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Billing.ChartOfAccounts',
    },
    {
      path: '/accounting/journal-entries',
      name: '::Menu:JournalEntries',
      parentName: '::Menu:Accounts',
      iconClass: 'fas fa-book',
      order: 32,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Billing.JournalEntries',
    },
    {
      path: '/accounting/reports',
      name: '::Menu:FinancialReports',
      parentName: '::Menu:Accounts',
      iconClass: 'fas fa-chart-line',
      order: 33,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Billing.FinancialReports',
    },
    {
      path: '/accounting/payment-vouchers',
      name: '::Menu:PaymentVouchers',
      parentName: '::Menu:Accounts',
      iconClass: 'fas fa-file-invoice-dollar',
      order: 34,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Billing.PaymentVouchers',
    },
    {
      path: '/accounting/receipt-vouchers',
      name: '::Menu:ReceiptVouchers',
      parentName: '::Menu:Accounts',
      iconClass: 'fas fa-receipt',
      order: 35,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Billing.ReceiptVouchers',
    },
    {
      path: '/accounting/bank-transactions',
      name: '::Menu:BankTransactions',
      parentName: '::Menu:Accounts',
      iconClass: 'fas fa-university',
      order: 36,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Billing.BankTransactions',
    },
    {
      path: '/accounting/claims',
      name: '::Menu:ContractClaims',
      parentName: '::Menu:Accounts',
      iconClass: 'fas fa-file-contract',
      order: 37,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Billing.ContractClaims',
    },
    {
      path: '/accounting/reports/daily',
      name: '::Menu:DailyAccountsReport',
      parentName: '::Menu:Accounts',
      iconClass: 'fas fa-calendar-day',
      order: 38,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Billing.FinancialReports.DailyReport',
    },
    {
      path: '/accounting/reports/debts',
      name: '::Menu:CustomerDebtsReport',
      parentName: '::Menu:Accounts',
      iconClass: 'fas fa-user-clock',
      order: 39,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Billing.FinancialReports.CustomerDebtsReport',
    },
    {
      path: '/accounting/reports/discounts',
      name: '::Menu:DiscountsReport',
      parentName: '::Menu:Accounts',
      iconClass: 'fas fa-percentage',
      order: 40,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Billing.FinancialReports.DiscountsReport',
    },
    {
      path: '/accounting/reports/income-statement',
      name: '::Menu:IncomeStatement',
      parentName: '::Menu:Accounts',
      iconClass: 'fas fa-file-invoice-dollar',
      order: 41,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Billing.FinancialReports.IncomeStatement',
    },
    {
      path: '/accounting/reports/balance-sheet',
      name: '::Menu:BalanceSheet',
      parentName: '::Menu:Accounts',
      iconClass: 'fas fa-balance-scale',
      order: 42,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Billing.FinancialReports.BalanceSheet',
    },
    {
      path: '/accounting/reports/account-statement',
      name: '::Menu:AccountStatement',
      parentName: '::Menu:Accounts',
      iconClass: 'fas fa-file-alt',
      order: 43,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Billing.FinancialReports.AccountStatement',
    },
    // Insurance
    {
      name: '::Menu:Insurance',
      iconClass: 'fas fa-shield-alt',
      order: 40,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Reception.InsuranceCompanies',
    },
    {
      path: '/reception/insurance-companies',
      name: '::Menu:InsuranceCompanies',
      parentName: '::Menu:Insurance',
      iconClass: 'fas fa-building',
      order: 41,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Reception.InsuranceCompanies',
    },
    {
      path: '/reception/insurance-plans',
      name: '::Menu:InsurancePlans',
      parentName: '::Menu:Insurance',
      iconClass: 'fas fa-file-contract',
      order: 42,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Reception.InsurancePlans',
    },
    {
      path: '/reports/insurance-reports',
      name: '::Menu:InsuranceReports',
      parentName: '::Menu:Insurance',
      iconClass: 'fas fa-chart-line',
      order: 43,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Reception.InsuranceCompanies',
    },
    // Billing
    {
      name: '::Menu:Billing',
      iconClass: 'fas fa-money-bill-wave',
      order: 50,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Billing',
    },
    {
      path: '/reception/invoices',
      name: '::Menu:Invoices',
      parentName: '::Menu:Billing',
      iconClass: 'fas fa-file-invoice',
      order: 51,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Reception.Invoices',
    },
    {
      path: '/reception/payments',
      name: '::Menu:Payments',
      parentName: '::Menu:Billing',
      iconClass: 'fas fa-cash-register',
      order: 52,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Reception.Payments',
    },
    {
      path: '/reception/deferred-payments',
      name: '::Menu:DeferredPayments',
      parentName: '::Menu:Billing',
      iconClass: 'fas fa-clock',
      order: 53,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Billing.DeferredPayments',
    },
    // Definitions
    {
      name: '::Menu:Definitions',
      iconClass: 'fas fa-cogs',
      order: 100,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Settings',
    },
    {
      path: '/settings/departments',
      name: '::Menu:Departments',
      parentName: '::Menu:Definitions',
      iconClass: 'fas fa-building',
      order: 101,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Settings',
    },
    {
      path: '/settings/specialties',
      name: '::Menu:Specialties',
      parentName: '::Menu:Definitions',
      iconClass: 'fas fa-stethoscope',
      order: 102,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Settings',
    },
    {
      path: '/settings/clinics',
      name: '::Menu:Clinics',
      parentName: '::Menu:Definitions',
      iconClass: 'fas fa-clinic-medical',
      order: 103,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Settings',
    },
    {
      path: '/settings/doctors',
      name: '::Menu:Doctors',
      parentName: '::Menu:Definitions',
      iconClass: 'fas fa-user-md',
      order: 104,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Settings',
    },
    {
      path: '/settings/laboratories',
      name: '::Menu:Laboratories',
      parentName: '::Menu:Definitions',
      iconClass: 'fas fa-flask',
      order: 105,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Settings',
    },
    {
      path: '/settings/doctor-schedule',
      name: '::Menu:DoctorSchedule',
      parentName: '::Menu:Definitions',
      iconClass: 'fas fa-clock',
      order: 106,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Settings',
    },
    {
      path: '/definitions/nationalities',
      name: '::Menu:Nationalities',
      parentName: '::Menu:Definitions',
      iconClass: 'fas fa-globe',
      order: 110,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Definitions.Nationalities',
    },
    {
      path: '/definitions/professions',
      name: '::Menu:Professions',
      parentName: '::Menu:Definitions',
      iconClass: 'fas fa-user-tie',
      order: 111,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Definitions.Professions',
    },
    {
      path: '/definitions/contracts',
      name: '::Menu:Contracts',
      parentName: '::Menu:Definitions',
      iconClass: 'fas fa-file-contract',
      order: 112,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Definitions.Contracts',
    },
    {
      path: '/definitions/patient-categories',
      name: '::Menu:PatientCategories',
      parentName: '::Menu:Definitions',
      iconClass: 'fas fa-tags',
      order: 113,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Definitions.PatientCategories',
    },
    {
      path: '/definitions/referral-sources',
      name: '::Menu:ReferralSources',
      parentName: '::Menu:Definitions',
      iconClass: 'fas fa-handshake',
      order: 114,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Definitions.ReferralSources',
    },
    {
      path: '/settings/job-titles',
      name: '::Menu:JobTitles',
      parentName: '::Menu:Definitions',
      iconClass: 'fas fa-user-tag',
      order: 115,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Settings',
    },
    {
      path: '/settings/pharmacy',
      name: '::Menu:PharmacySettings',
      parentName: '::Menu:Settings',
      iconClass: 'fas fa-pills',
      order: 1,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Settings',
    },
    {
      path: '/appointments/waiting-list',
      name: '::Menu:WaitingList',
      parentName: '::Menu:Appointments',
      iconClass: 'fas fa-list-ol',
      order: 23,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Appointments',
    },
    {
      path: '/appointments/flow',
      name: '::Menu:ClinicFlow',
      parentName: '::Menu:Appointments',
      iconClass: 'fas fa-stream',
      order: 24,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Appointments',
    },
    // Laboratory
    {
      name: '::Menu:Laboratory',
      iconClass: 'fas fa-vials',
      order: 25,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Laboratory',
    },
    {
      path: '/laboratory/catalog',
      name: '::Menu:LabCatalog',
      parentName: '::Menu:Laboratory',
      iconClass: 'fas fa-book-medical',
      order: 1,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Laboratory.Catalog',
    },
    {
      path: '/laboratory/requests',
      name: '::Menu:LabRequests',
      parentName: '::Menu:Laboratory',
      iconClass: 'fas fa-microscope',
      order: 2,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Laboratory.Requests',
    },
    {
      path: '/laboratory/appointments',
      name: '::Menu:LabAppointments',
      parentName: '::Menu:Laboratory',
      iconClass: 'fas fa-calendar-alt',
      order: 3,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Laboratory.Appointments',
    },
    // Radiology Department
    {
      name: '::Menu:RadiologyDept',
      iconClass: 'fas fa-x-ray',
      order: 26,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Radiology',
    },
    {
      path: '/radiology/requests',
      name: '::Menu:RadiologyWorklist',
      parentName: '::Menu:RadiologyDept',
      iconClass: 'fas fa-clipboard-list',
      order: 1,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Radiology.Requests',
    },
    {
      path: '/radiology/results',
      name: '::Menu:RadiologyArchives',
      parentName: '::Menu:RadiologyDept',
      iconClass: 'fas fa-file-invoice',
      order: 2,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Radiology.Requests',
    },
    {
      name: '::Menu:Emergency',
      iconClass: 'fas fa-ambulance',
      order: 30,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Emergency',
    },
    // Pharmacy
    {
      name: '::Menu:Pharmacy',
      iconClass: 'fas fa-pills',
      order: 28,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Pharmacy',
    },
    {
      path: '/pharmacy',
      name: '::Menu:Prescriptions',
      parentName: '::Menu:Pharmacy',
      iconClass: 'fas fa-file-prescription',
      order: 1,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Pharmacy.Prescriptions',
    },
    {
      path: '/pharmacy/stock',
      name: '::Menu:Stock',
      parentName: '::Menu:Pharmacy',
      iconClass: 'fas fa-cubes',
      order: 2,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Pharmacy.Stock',
    },
    {
      path: '/pharmacy/drugs',
      name: '::Menu:Drugs',
      parentName: '::Menu:Pharmacy',
      iconClass: 'fas fa-capsules',
      order: 3,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Pharmacy.Drugs',
    },
    {
      path: '/pharmacy/dispensing',
      name: '::Menu:DispensingVerification',
      parentName: '::Menu:Pharmacy',
      iconClass: 'fas fa-check-double',
      order: 4,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Pharmacy.Dispensing',
    },
    {
      path: '/pharmacy/pos',
      name: '::Menu:POS',
      parentName: '::Menu:Pharmacy',
      iconClass: 'fas fa-cash-register',
      order: 5,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Pharmacy.POS',
    },
    {
      path: '/pharmacy/inpatient-requests',
      name: '::Menu:InpatientRequests',
      parentName: '::Menu:Pharmacy',
      iconClass: 'fas fa-bed',
      order: 6,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Pharmacy',
    },
    {
      path: '/emergency/dashboard',
      name: '::Menu:EmergencyDashboard',
      parentName: '::Menu:Emergency',
      iconClass: 'fas fa-heartbeat',
      order: 1,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Emergency.Dashboard',
    },
    // Services & Pricing
    {
      path: '/services',
      name: '::Menu:Services',
      parentName: '::Menu:Definitions',
      iconClass: 'fas fa-briefcase-medical',
      order: 107,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Definitions.Services',
    },
    {
      path: '/services/radiology',
      name: '::Menu:Radiology',
      parentName: '::Menu:Definitions',
      iconClass: 'fas fa-x-ray',
      order: 108,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Definitions.Radiology',
    },
    {
      path: '/services/price-lists',
      name: '::Menu:PriceLists',
      parentName: '::Menu:Definitions',
      iconClass: 'fas fa-tags',
      order: 109,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Definitions.PriceLists',
    },
    {
      path: '/definitions/payment-methods',
      name: '::Menu:PaymentMethods',
      parentName: '::Menu:Definitions',
      iconClass: 'fas fa-credit-card',
      order: 110,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Definitions.PaymentMethods',
    },
    // Administration
    {
      path: '/identity',
      name: '::Menu:UserManagement',
      iconClass: 'fas fa-users-cog',
      order: 200,
      layout: eLayoutType.application,
    },
    {
      path: '/admin/activity-logs',
      name: '::Menu:ActivityLogs',
      iconClass: 'fas fa-history',
      order: 210,
      layout: eLayoutType.application,
    },
    // Inventory
    {
      name: '::Menu:Inventory',
      iconClass: 'fas fa-boxes',
      order: 35,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Inventory',
    },
    {
      path: '/inventory/dashboard',
      name: '::Menu:InventoryDashboard',
      parentName: '::Menu:Inventory',
      iconClass: 'fas fa-tachometer-alt',
      order: 36,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Inventory.Dashboard',
    },
    {
      path: '/inventory/warehouse-management',
      name: '::Menu:WarehouseManagement',
      parentName: '::Menu:Inventory',
      iconClass: 'fas fa-warehouse',
      order: 37,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Inventory.ManageWarehouses',
    },
    {
      path: '/inventory/suppliers',
      name: '::Menu:Suppliers',
      parentName: '::Menu:Inventory',
      iconClass: 'fas fa-truck',
      order: 38,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Inventory.Suppliers',
    },
    {
      path: '/inventory/purchase-requisitions',
      name: '::Menu:PurchaseRequisitions',
      parentName: '::Menu:Inventory',
      iconClass: 'fas fa-file-invoice',
      order: 38,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Inventory.PurchaseRequisitions',
    },
    {
      path: '/inventory/purchase-orders',
      name: '::Menu:PurchaseOrders',
      parentName: '::Menu:Inventory',
      iconClass: 'fas fa-shopping-cart',
      order: 39,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Inventory.PurchaseOrders',
    },

    {
      path: '/inventory/inventory-counting',
      name: '::Menu:InventoryCounting',
      parentName: '::Menu:Inventory',
      iconClass: 'fas fa-clipboard-check',
      order: 40,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Inventory.StockOperations',
    },
    {
      path: '/inventory/purchase-invoices',
      name: '::Menu:PurchaseInvoices',
      parentName: '::Menu:Inventory',
      iconClass: 'fas fa-file-invoice-dollar',
      order: 40,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Inventory.PurchaseOrders',
    },
    {
      path: '/inventory/reports/department-consumption',
      name: '::Menu:DepartmentalConsumption',
      parentName: '::Menu:Reports',
      iconClass: 'fas fa-chart-line',
      order: 40,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Inventory.StockOperations', // Use an existing generic permission for now
    },
    {
      path: '/inventory/reports/low-stock',
      name: '::Menu:LowStockReport',
      parentName: '::Menu:Reports',
      iconClass: 'fas fa-exclamation-triangle',
      order: 41,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Inventory.StockOperations',
    },
    {
      path: '/inventory/reports/stagnant-stock',
      name: '::Menu:StagnantStockReport',
      parentName: '::Menu:Reports',
      iconClass: 'fas fa-box-open',
      order: 42,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Inventory.StockOperations',
    },
    // Nursing
    {
      name: '::Menu:Nursing',
      iconClass: 'fas fa-user-nurse',
      order: 60,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Nursing',
    },
    {
      path: '/nursing/patient-list',
      name: '::Menu:PatientList',
      parentName: '::Menu:Nursing',
      iconClass: 'fas fa-list',
      order: 1,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Nursing.PatientList',
    },
    {
      path: '/nursing/shift-handover',
      name: '::Menu:ShiftHandover',
      parentName: '::Menu:Nursing',
      iconClass: 'fas fa-exchange-alt',
      order: 2,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Nursing.ShiftHandover',
    },
    {
      path: '/nursing/internal-requests',
      name: '::Menu:NursingInternalRequests',
      parentName: '::Menu:Nursing',
      iconClass: 'fas fa-clipboard-check',
      order: 3,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Nursing',
    },
    // Inpatient
    {
      name: '::Menu:Inpatient',
      iconClass: 'fas fa-bed',
      order: 70,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Inpatient',
    },
    {
      path: '/inpatient/dashboard',
      name: '::Menu:InpatientDashboard',
      parentName: '::Menu:Inpatient',
      iconClass: 'fas fa-tachometer-alt',
      order: 1,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Inpatient.Dashboard',
    },
    {
      path: '/inpatient/rooms',
      name: '::Menu:Rooms',
      parentName: '::Menu:Inpatient',
      iconClass: 'fas fa-door-open',
      order: 2,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Inpatient.Rooms',
    },
    {
      path: '/inpatient/reservations',
      name: '::Menu:Reservations',
      parentName: '::Menu:Inpatient',
      iconClass: 'fas fa-calendar-alt',
      order: 3,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Inpatient.Reservations',
    },
    {
      path: '/inpatient/admissions',
      name: '::Menu:Admissions',
      parentName: '::Menu:Inpatient',
      iconClass: 'fas fa-clipboard-list',
      order: 4,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Inpatient.Admissions',
    },
    // HR
    {
      name: '::Menu:HR',
      iconClass: 'fas fa-users',
      order: 75,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.HR',
    },
    {
      path: '/hr/employees',
      name: '::Menu:Employees',
      parentName: '::Menu:HR',
      iconClass: 'fas fa-id-card',
      order: 1,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.HR.Employees',
    },
    {
      path: '/hr/attendance',
      name: '::Menu:Attendance',
      parentName: '::Menu:HR',
      iconClass: 'fas fa-user-clock',
      order: 2,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.HR.Attendance',
    },
    {
      path: '/hr/daily-attendance',
      name: '::Menu:DailyAttendance',
      parentName: '::Menu:HR',
      iconClass: 'fas fa-fingerprint',
      order: 3,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.HR.Attendance',
    },
    {
      path: '/hr/leaves',
      name: '::Menu:EmployeeLeaves',
      parentName: '::Menu:HR',
      iconClass: 'fas fa-calendar-minus',
      order: 3,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.HR.EmployeeLeaves',
    },
    {
      path: '/hr/loans',
      name: '::Menu:Loans',
      parentName: '::Menu:HR',
      iconClass: 'fas fa-hand-holding-usd',
      order: 4,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.HR.Loans',
    },
    {
      path: '/hr/penalties',
      name: '::Menu:Penalties',
      parentName: '::Menu:HR',
      iconClass: 'fas fa-exclamation-circle',
      order: 5,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.HR.Penalties',
    },
    {
      path: '/hr/payroll',
      name: '::Menu:Payroll',
      parentName: '::Menu:HR',
      iconClass: 'fas fa-money-check-alt',
      order: 6,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.HR.Payroll',
    },
    {
      path: '/hr/compensation-items',
      name: '::Menu:CompensationItems',
      parentName: '::Menu:HR',
      iconClass: 'fas fa-layer-group',
      order: 7,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.HR.CompensationItems',
    },
    {
      path: '/hr/reports',
      name: '::Menu:HRReports',
      parentName: '::Menu:HR',
      iconClass: 'fas fa-chart-bar',
      order: 8,
      layout: eLayoutType.application,
    },
    // Operations
    {
      name: '::Menu:Operations',
      iconClass: 'fas fa-procedures',
      order: 80,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Operations',
    },
    {
      path: '/operations/surgical-operations',
      name: '::Menu:SurgicalOperations',
      parentName: '::Menu:Operations',
      iconClass: 'fas fa-scalpel',
      order: 1,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Operations',
    },
    {
      name: '::Menu:Reports',
      iconClass: 'fas fa-chart-bar',
      order: 400,
      layout: eLayoutType.application,
    },
    {
      path: '/operations/reports/surgical-operations',
      name: '::Menu:OperationsReport',
      parentName: '::Menu:Reports',
      iconClass: 'fas fa-file-medical-alt',
      order: 1,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Operations.Report',
    },
    {
      path: '/patients/services-report',
      name: '::PatientServicesReport',
      parentName: '::Menu:Reports',
      iconClass: 'fas fa-file-invoice-dollar',
      order: 2,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Patients',
    },
    {
      path: '/reports/paid-tickets',
      name: '::Menu:PaidTickets',
      parentName: '::Menu:Reports',
      iconClass: 'fas fa-ticket-alt',
      order: 3,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Operations.Report',
    },
    {
      path: '/reports/pharmacy-sales',
      name: '::Menu:PharmacySales',
      parentName: '::Menu:Reports',
      iconClass: 'fas fa-pills',
      order: 4,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Operations.Report',
    },
    {
      path: '/reports/insurance-reports',
      name: '::Menu:InsuranceReports',
      parentName: '::Menu:Reports',
      iconClass: 'fas fa-shield-alt',
      order: 5,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Reception.InsuranceCompanies',
    },
    {
      path: '/setting-management',
      name: '::Menu:Settings',
      iconClass: 'fas fa-cog',
      order: 300,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Settings',
    }
    // Force rebuild 2
  ]);
}
