import { RoutesService, eLayoutType } from '@abp/ng.core';
import { inject, provideAppInitializer } from '@angular/core';

export const APP_ROUTE_PROVIDER = [
  provideAppInitializer(() => {
    configureRoutes();
  }),
];

function configureRoutes() {
  const routes = inject(RoutesService);
  routes.add([
    // Home
    {
      path: '/',
      name: '::Menu:Home',
      iconClass: 'fas fa-home',
      order: 1,
      layout: eLayoutType.application,
    },
    // Reception
    {
      name: '::Menu:Reception',
      iconClass: 'fas fa-hospital-user',
      order: 10,
      layout: eLayoutType.application,
    },
    {
      path: '/reception/laboratory-reception',
      name: '::Menu:Tickets',
      parentName: '::Menu:Reception',
      iconClass: 'fas fa-ticket-alt',
      order: 1,
      layout: eLayoutType.application,
    },
    {
      path: '/patients',
      name: '::Menu:Patients',
      parentName: '::Menu:Reception',
      iconClass: 'fas fa-user-injured',
      order: 2,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Patients',
    },
    // Appointments
    {
      name: '::Menu:Appointments',
      iconClass: 'fas fa-calendar-check',
      order: 20,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Appointments',
    },
    {
      path: '/appointments/booking',
      name: '::Menu:BookNewAppointment',
      parentName: '::Menu:Appointments',
      iconClass: 'fas fa-calendar-plus',
      order: 21,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Appointments.Create',
    },
    {
      path: '/appointments/my-appointments',
      name: '::Menu:MyAppointments',
      parentName: '::Menu:Appointments',
      iconClass: 'fas fa-list-alt',
      order: 22,
      layout: eLayoutType.application,
    },
    // Accounts (Financials)
    {
      name: '::Menu:Accounts',
      iconClass: 'fas fa-file-invoice-dollar',
      order: 30,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Billing',
    },
    {
      path: '/accounting/chart-of-accounts',
      name: '::Menu:ChartOfAccounts',
      parentName: '::Menu:Accounts',
      iconClass: 'fas fa-sitemap',
      order: 31,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Billing.ChartOfAccounts',
    },
    {
      path: '/accounting/journal-entries',
      name: '::Menu:JournalEntries',
      parentName: '::Menu:Accounts',
      iconClass: 'fas fa-book',
      order: 32,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Billing.JournalEntries',
    },
    // Insurance
    {
      name: '::Menu:Insurance',
      iconClass: 'fas fa-shield-alt',
      order: 40,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Billing',
    },
    {
      path: '/reception/insurance-companies',
      name: '::Menu:InsuranceCompanies',
      parentName: '::Menu:Insurance',
      iconClass: 'fas fa-building',
      order: 41,
      layout: eLayoutType.application,
    },
    {
      path: '/reception/insurance-plans',
      name: '::Menu:InsurancePlans',
      parentName: '::Menu:Insurance',
      iconClass: 'fas fa-file-contract',
      order: 42,
      layout: eLayoutType.application,
    },
    // Billing
    {
      name: '::Menu:Billing',
      iconClass: 'fas fa-money-bill-wave',
      order: 50,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Billing',
    },
    {
      path: '/reception/invoices',
      name: '::Menu:Invoices',
      parentName: '::Menu:Billing',
      iconClass: 'fas fa-file-invoice',
      order: 51,
      layout: eLayoutType.application,
    },
    {
      path: '/reception/payments',
      name: '::Menu:Payments',
      parentName: '::Menu:Billing',
      iconClass: 'fas fa-cash-register',
      order: 52,
      layout: eLayoutType.application,
    },
    {
      path: '/reception/deferred-payments',
      name: '::Menu:DeferredPayments',
      parentName: '::Menu:Billing',
      iconClass: 'fas fa-clock',
      order: 53,
      layout: eLayoutType.application,
    },
    // Definitions
    {
      name: '::Menu:Definitions',
      iconClass: 'fas fa-cogs',
      order: 100,
      layout: eLayoutType.application,
      // requiredPolicy: 'HIS.Settings', // Removed to allow granular child control
    },
    {
      path: '/settings/departments',
      name: '::Menu:Departments',
      parentName: '::Menu:Definitions',
      iconClass: 'fas fa-building',
      order: 101,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Settings',
    },
    {
      path: '/settings/specialties',
      name: '::Menu:Specialties',
      parentName: '::Menu:Definitions',
      iconClass: 'fas fa-stethoscope',
      order: 102,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Settings',
    },
    {
      path: '/settings/clinics',
      name: '::Menu:Clinics',
      parentName: '::Menu:Definitions',
      iconClass: 'fas fa-clinic-medical',
      order: 103,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Settings',
    },
    {
      path: '/settings/doctors',
      name: '::Menu:Doctors',
      parentName: '::Menu:Definitions',
      iconClass: 'fas fa-user-md',
      order: 104,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Settings',
    },
    {
      path: '/settings/laboratories',
      name: '::Menu:Laboratories',
      parentName: '::Menu:Definitions',
      iconClass: 'fas fa-flask',
      order: 105,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Laboratory',
    },
    {
      path: '/settings/doctor-schedule',
      name: '::Menu:DoctorSchedule',
      parentName: '::Menu:Definitions',
      iconClass: 'fas fa-clock',
      order: 106,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Settings',
    },
    {
      path: '/definitions/nationalities',
      name: '::Menu:Nationalities',
      parentName: '::Menu:Definitions',
      iconClass: 'fas fa-globe',
      order: 110,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Settings',
    },
    {
      path: '/definitions/professions',
      name: '::Menu:Professions',
      parentName: '::Menu:Definitions',
      iconClass: 'fas fa-user-tie',
      order: 111,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Settings',
    },
    {
      path: '/definitions/contracts',
      name: '::Menu:Contracts',
      parentName: '::Menu:Definitions',
      iconClass: 'fas fa-file-contract',
      order: 112,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Settings',
    },
    {
      path: '/definitions/patient-categories',
      name: '::Menu:PatientCategories',
      parentName: '::Menu:Definitions',
      iconClass: 'fas fa-tags',
      order: 113,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Settings',
    },
    {
      path: '/definitions/referral-sources',
      name: '::Menu:ReferralSources',
      parentName: '::Menu:Definitions',
      iconClass: 'fas fa-handshake',
      order: 114,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Settings',
    },
    {
      path: '/appointments/waiting-list',
      name: '::Menu:WaitingList',
      parentName: '::Menu:Appointments',
      iconClass: 'fas fa-list-ol',
      order: 23,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Appointments',
    },
    {
      path: '/appointments/flow',
      name: '::Menu:ClinicFlow',
      parentName: '::Menu:Appointments',
      iconClass: 'fas fa-stream',
      order: 24,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Appointments',
    },
    // Laboratory
    {
      name: '::Menu:Laboratory',
      iconClass: 'fas fa-vials',
      order: 25,
      layout: eLayoutType.application,
    },
    {
      path: '/laboratory/catalog',
      name: '::Menu:LabCatalog',
      parentName: '::Menu:Laboratory',
      iconClass: 'fas fa-book-medical',
      order: 1,
      layout: eLayoutType.application,
    },
    {
      path: '/laboratory/requests',
      name: '::Menu:LabRequests',
      parentName: '::Menu:Laboratory',
      iconClass: 'fas fa-microscope',
      order: 2,
      layout: eLayoutType.application,
    },
    {
      path: '/laboratory/appointments',
      name: '::Menu:LabAppointments',
      parentName: '::Menu:Laboratory',
      iconClass: 'fas fa-calendar-alt',
      order: 3,
      layout: eLayoutType.application,
    },
    {
      name: '::Menu:Emergency',
      iconClass: 'fas fa-ambulance',
      order: 30,
      layout: eLayoutType.application,
    },
    // Pharmacy
    {
      name: '::Menu:Pharmacy',
      iconClass: 'fas fa-pills',
      order: 28,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Pharmacy',
    },
    {
      path: '/pharmacy',
      name: '::Menu:Prescriptions',
      parentName: '::Menu:Pharmacy',
      iconClass: 'fas fa-file-prescription',
      order: 1,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Pharmacy.Prescriptions',
    },
    {
      path: '/pharmacy/stock',
      name: '::Menu:Stock',
      parentName: '::Menu:Pharmacy',
      iconClass: 'fas fa-cubes',
      order: 2,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Pharmacy.Stock',
    },
    {
      path: '/pharmacy/drugs',
      name: '::Menu:Drugs',
      parentName: '::Menu:Pharmacy',
      iconClass: 'fas fa-capsules',
      order: 3,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Pharmacy.Drugs',
    },
    {
      path: '/emergency/dashboard',
      name: '::Menu:EmergencyDashboard',
      parentName: '::Menu:Emergency',
      iconClass: 'fas fa-heartbeat',
      order: 1,
      layout: eLayoutType.application,
    },
    // Services & Pricing
    {
      path: '/services',
      name: '::Menu:Services',
      parentName: '::Menu:Definitions',
      iconClass: 'fas fa-briefcase-medical',
      order: 107,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Settings',
    },
    {
      path: '/services/radiology',
      name: '::Menu:Radiology',
      parentName: '::Menu:Definitions',
      iconClass: 'fas fa-x-ray',
      order: 108,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Settings',
    },
    {
      path: '/services/price-lists',
      name: '::Menu:PriceLists',
      parentName: '::Menu:Definitions',
      iconClass: 'fas fa-tags',
      order: 109,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Settings',
    },
    // Administration
    {
      path: '/identity',
      name: '::Menu:UserManagement',
      iconClass: 'fas fa-users-cog',
      order: 200,
      layout: eLayoutType.application,
      requiredPolicy: 'AbpIdentity.Users',
    },
    {
      path: '/admin/activity-logs',
      name: '::Menu:ActivityLogs',
      iconClass: 'fas fa-history',
      order: 210,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Settings',
    },
    // Inventory
    {
      name: '::Menu:Inventory',
      iconClass: 'fas fa-boxes',
      order: 35,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Inventory',
    },
    {
      path: '/inventory/dashboard',
      name: '::Menu:InventoryDashboard',
      parentName: '::Menu:Inventory',
      iconClass: 'fas fa-tachometer-alt',
      order: 36,
      layout: eLayoutType.application,
    },
    {
      path: '/inventory/warehouse-management',
      name: '::Menu:WarehouseManagement',
      parentName: '::Menu:Inventory',
      iconClass: 'fas fa-warehouse',
      order: 37,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Inventory.ManageWarehouses',
    },
    {
      path: '/setting-management',
      name: '::Menu:Settings',
      iconClass: 'fas fa-cog',
      order: 300,
      layout: eLayoutType.application,
      requiredPolicy: 'HIS.Settings',
    }
  ]);
}
