import * as Dtos from './dtos';
export * from './clinic.service';
export * from './department.service';
export * from './doctor.service';
export * from './hospital-settings.service';
export * from './inpatient-settings.service';
export * from './job-title.service';
export * from './laboratory.service';
export * from './models';
export * from './pharmacy-settings.service';
export * from './specialty.service';
export { Dtos };
